### ISSUE TITLE
eg1.bd not found 

### ISSUE THREAD

**Issue by salsicha** [petercorke/bdsim#11]
Hi, nice project. Quick question:

I'm following your README and trying to run the graphical editor. When I navigate to the examples folder and type "bdedit eg1.bd", I get "ValueError: bdfile eg1.py not found".

Obviously the file doesn't exist, but there doesn't seem to be any *.bd files in the repo. Can you provide example .bd files? Why are they not present?

Thanks!

**Comment by petercorke** [comment]
sorry to be slow.

It should have said `eg1.bd` not found rather than `eg1.py`.

I've just done a bit of polishing and `eg1.bd` is there now.
