### ISSUE TITLE
INTEGRATOR into LTI_SS block fails

### ISSUE THREAD

**Issue by dgrunberg** [petercorke/bdsim#20]
For bugs with the graphical tool `bdedit` please use the `bdedit` bug report template.

**BUG**
connecting output of INTEGRATOR to LTI_SS (or LTI_SISO) block fails with this error message:

[lti_siso block: PLANT.deriv]: exception AssertionError
  deriv: block PLANT returns wrong shape (4,), should be (2,)

  File "/home/grunberg/algopower/bdsim2/bdsim/blockdiagram.py", line 1128, in deriv
    raise AssertionError(

input 0 from integrator.0 [ndarray]
   [0.]
**To Reproduce**
```
#!/usr/bin/env python
import sys
import numpy as np
import bdsim

print(f'Python {sys.version=}')
#print(f'bdsim version {bdsim.__version__}')
print(f'numpy version {np.__version__}')

sim = bdsim.BDSim()
bd = sim.blockdiagram()

tc1=10
tc2=40
a=1/tc1
b=1/tc2
num = [a*b]
den = [1, a+b, a*b]

# blocks
ref = bd.STEP(T=1, off=0, on=1.0,name='ref')
integrator = bd.INTEGRATOR(gain=1)
#gain = bd.GAIN(5)
plant = bd.LTI_SISO(num, den, name='PLANT')
# connections
bd.connect(ref, integrator)
bd.connect(integrator, plant)

print(bd.blocklist)
bd.compile(verbose=False)
sim.report(bd)
out = sim.run(bd, 5)
print(out)
```
**Expected behavior**
Should compile and run without error
**Operating environment (please complete the following information):**
 - OS: Linux 5.15.0-67 LTS 22.04
 - Version bdsim (current from github), numpy 1.25.0

**Additional context**
Looking at the inputs to the deriv method of the LTI_SS class in the example above:
The problem is that ref (in the example above) from a STEP is a signal u=[1.0], but the output of the INTEGRATOR block is u=[array([1.0])].  In the LTI_SS.deriv function,  self.B @ np.array(u) causes a problem, as the STEP signal makes this shape (2,) vs. INTEGRATOR output shape (2,1).  Since the A@x shape is (2,)   adding a shape (2,)  to a shape (2,1) causes broadcasting and produces a shape (2,2) which is then flattened into (4,) which is the wrong number of outputs.

I will post a pull request fix which corrects this in LTS_SS.deriv.  An alterative fix to change the output of the INTEGRATOR block to match STEP output - the choice of fix depends on other blocks and if the two signals here are OK or whether all signals should be forced to a list of floats rather than a list of arrays.

**Comment by petercorke** [comment]
I think we have a working PID function now. thanks for pushing this along.
