### ISSUE TITLE
what am I missing?

### ISSUE THREAD

**Issue by RezaArghand** [petercorke/bdsim#6]
Hi, good job. this is a very useful software 
I'm trying to use PSO optimization algorithm along with your software, but in the first step, I can not run any example of your software and I have no idea why!
I installed all modules except spatialmath, because it can not be installed. I installed spatialmath-python instead that I think it is ok.
I downloaded the project, and want to run eg1.py in example folder and I get some errors. what is going wrong? can you help me please?
this is one of my errors:

Traceback (most recent call last):
  File "C:\Users\argha\Desktop\rasa\bdsim-master\bdsim-master\examples\eg1.py", line 8, in <module>
    sim.blocks()
AttributeError: 'BDSim' object has no attribute 'blocks'
![error](https://user-images.githubusercontent.com/41468506/150172666-7cb0fe59-c3d6-47a5-869a-f62adf13e83a.JPG)

thank you in advance...

**Comment by petercorke** [comment]
you say "download", did you clone the repo?  The pip version is way out of date, but changes have been happening quickly recently and I've not been updating PyPi

**Comment by petercorke** [comment]
"I installed all modules except spatialmath, because it can not be installed. I installed spatialmath-python instead that I think it is ok."  Am confused by this, not sure what you mean by "spatialmath" but "spatialmath-python" is what you need.

**Comment by mrrigidbody** [comment]
thanks for the answer. 
I cloned the bdsim and run the eg1.py example again, but I've got another error. 
![error](https://user-images.githubusercontent.com/41468506/150343931-f478c9ff-70c9-4303-8f1f-f7edb7eaa64c.JPG)

**Comment by petercorke** [comment]
Ok, the fact I had 24 unpushed commits might be an issue. sorry.  do a git pull and see how it goes.

**Comment by petercorke** [comment]
Did you get anywhere with this?
